package com.zhanyage.bindview.compile.utils;

/**
 * Created by andya on 2019/4/12
 * Describe: Constant pool
 */
public class Constants {

    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "bindView";
    public static final String NAME_OF_BINDVIEW = SEPARATOR + PROJECT + SEPARATOR + "BindView";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY BINDVIEW.";
    public static final String ANNOTATION_PACKAGE = "com.zhanyage.bindview";

    //log
    static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";

    //Custom interface
    public static final String BIND_TEMPLATE_PACKAGE = "com.zhanyage.bindview.core";
    public static final String TEMPLATE_PACKAGE = ".template";
    public static final String IBINDTEMPLATE = "BindTemplate";

    // System service
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String VIEW_TYPE = "android.view.View";

    //Method and Parameter
    public static final String PARAMETER_TARGET = "target";
    public static final String PARAMETER_VIEW_TARGET = "viewTarget";
    public static final String METHOD_BINDTARGETVIEW = "bindTargetView";

    //Annotation type
    public static final String ANNOTATION_TYPE_BIND = ANNOTATION_PACKAGE + ".annotation.Bind";

}
